guestbook-rails-minimal/config/routes.rb
Rails.application.routes.draw do
  resources :guestbook_entries
  resources :generated_guestbook_entries, only: [:new, :create, :update]
  resources :messages
  resources :entries
  namespace :guestbook_with_ai do
    resources :entries
    root "entries#index"
  end
  namespace :guestbook_with_ai_full do
    resources :entries
    root "entries#index"
  end
  resources :seed, only: :index
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  if Rails.env.local?
    # a test only route used by spec/features/it_works_spec.rb
    get "test_root", to: "rails/welcome#index", as: "test_root_rails"
  end

  # Defines the root path route ("/")
  root "home#index"
end

guestbook-rails-minimal/app/models/entry.rb
class Entry < ApplicationRecord
  # NOTE: use SQL over AREL
  #       eg Entry.published_arel.to_sql
  scope :published, -> { published_sql }
  scope :published_arel, -> {
    entry = arel_table
    Entry.where(
      entry[:generate_ai_text].eq(true)
        .and(entry[:use_generated_text].eq(true))
        .and(entry[:generated_text].not_eq(nil))
    .or(
      entry[:use_generated_text].eq(false)
    )
    )
  }
  scope :published_sql, -> {
    where(
      <<~EO_SQL.squish
        (
          generate_ai_text = 1
          AND use_generated_text = 1
          AND generated_text IS NOT NULL
        ) OR (
          use_generated_text = 0
        )
      EO_SQL
    )
  }
  validates :name, presence: true, allow_blank: false
  validates :text, presence: true, allow_blank: false
end

guestbook-rails-minimal/app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[show edit update destroy]

  # GET /entries
  def index
    @entries = Entry.all
  end

  # GET /entries/1
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  def create
    @entry = Entry.new(entry_params)

    if @entry.save
      redirect_to entries_path, notice: "Entry was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /entries/1
  def update
    if @entry.update(entry_params)
      redirect_to @entry, notice: "Entry was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /entries/1
  def destroy
    @entry.destroy!
    redirect_to entries_url, notice: "Entry was successfully destroyed.", status: :see_other
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_entry
    @entry = Entry.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def entry_params
    params.require(:entry).permit(:title, :text, :name, :date)
  end
end

guestbook-rails-minimal/app/controllers/guestbook_with_ai/entries_controller.rb
module GuestbookWithAI
  class EntriesController < ApplicationController
    before_action :set_entry, only: %i[update]

    # GET /entries
    def index
      @entries = Entry.published
    end

    # GET /entries/new
    def new
      @entry = Entry.new
    end

    # POST /entries
    def create
      @entry = Entry.new(entry_params)

      if @entry.save
        if @entry.generate_ai_text && @entry.generated_text.blank?
          flash.now[:notice] = "AI is generating the response, please wait..."
          render :new, status: :ok
        else
          redirect_to guestbook_with_ai_root_path, notice: "Entry was successfully created."
        end
      else
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /entries/1
    def update
      if @entry.update(entry_params) && @entry.generate_ai_text && @entry.generated_text.present?
        redirect_to guestbook_with_ai_root_path, notice: "Entry was successfully created."
      elsif @entry.update(entry_params) && !@entry.generate_ai_text
        redirect_to guestbook_with_ai_root_path, notice: "Entry was successfully created."
      else
        flash.now[:notice] = "AI is generating the response, please wait..."
        render :edit, status: :unprocessable_entity
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(
        :title,
        :text,
        :name,
        :date,
        :generate_ai_text,
        :use_generated_text
      )
    end
  end
end

guestbook-rails-minimal/app/controllers/guestbook_with_ai_full/entries_controller.rb
module GuestbookWithAIFull
  class EntriesController < ApplicationController
    before_action :set_entry, only: %i[update]

    # GET /entries
    def index
      @entries = Entry.published
    end

    # GET /entries/new
    def new
      @entry = Entry.new
    end

    # POST /entries
    def create
      @entry = Entry.new(params[:entry])

      if @entry.save
        if @entry.generate_ai_text?
          # TODO: move to a better place
          # LAB 3 - START CODE
          generate_text_job = GenerateAITextJob.perform_later(@entry)
          @entry.update!(generate_job_id: generate_text_job.job_id)
          # LAB 3 - END CODE
          flash.now[:notice] = "AI is generating the response, please wait..."
          render :new, status: :ok
        else
          redirect_to guestbook_with_ai_full_root_path, notice: "Entry was successfully created."
        end
      else
        render :new, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /entries/1
    def update
      # TODO: check if still processing? or don't let it come here
      if params[:button] == "check"
        flash.now[:notice] = if @entry.generated_text.present? && @entry.generate_job_id.blank?
          "AI generation complete"
        else
          "AI is generating the response, please wait..."
        end
        render :new, status: :ok
      elsif @entry.update(params[:entry]) && @entry.generate_ai_text && @entry.generated_text.present?
        redirect_to guestbook_with_ai_full_root_path, notice: "Entry was successfully created."
      elsif @entry.update(params[:entry]) && @entry.generate_ai_text && @entry.generated_text.blank?
        flash.now[:notice] = "AI is generating the response, please wait..."
        render :new, status: :ok
      elsif @entry.update(params[:entry]) && !@entry.generate_ai_text
        redirect_to guestbook_with_ai_full_root_path, notice: "Entry was successfully created."
      else
        render :edit, status: :unprocessable_entity
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # NOTE: sepcifying each individual parameter is a more secure way of doing parameters
    # Only allow a list of trusted parameters through.
    # def entry_params
    #   params.require(:entry).permit(
    #     :title,
    #     :text,
    #     :name,
    #     :date,
    #     :generate_ai_text,
    #     :use_generated_text
    #   )
    # end
  end
end

guestbook-rails-minimal/app/views/guestbook_with_ai/entries/_entry.html.erb
<div id="<%= dom_id entry %>" data-testid="entry-<%= dom_id entry %>">
  <p>
    <strong>Text:</strong>
    <span data-testid="entry-text"><%= entry.text %></span>
  </p>

  <p>
    <strong>Name:</strong>
    <%= entry.name %>
  </p>
</div>

guestbook-rails-minimal/app/views/guestbook_with_ai/entries/_form.html.erb
<p style="color: green"><%= notice %></p>

<%= form_with(model: [:guestbook_with_ai, entry]) do |form| %>
  <% if entry.errors.any? %>
    <div style="color: red" data-testid="error-message">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
        <% entry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_field :text %>
  </div>

  <div>
    <%= form.label :generate_ai_text %>
    <%= form.check_box :generate_ai_text %>
  </div>

  <div>
    <%= form.label :generated_text, style: "display: block" %>
    <%= form.text_field :generated_text, disabled: true %>
  </div>

  <div>
    <%= form.label :use_generated_text %>
    <%= form.check_box :use_generated_text, disabled: !form.object.generated_text.present? %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

guestbook-rails-minimal/app/views/guestbook_with_ai/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render "form", entry: @entry %>

<br>

<div>
  <%= link_to "Back to entries", guestbook_with_ai_entries_path %>
</div>

guestbook-rails-minimal/app/views/guestbook_with_ai/entries/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Entries</h1>

<div id="entries">
  <% @entries.each do |entry| %>
    <%= render entry %>
  <% end %>
</div>

<%= link_to "New entry", new_guestbook_with_ai_entry_path %>

guestbook-rails-minimal/app/views/guestbook_with_ai/entries/new.html.erb
<h1>New entry</h1>

<%= render "form", entry: @entry %>

<br>

<div>
  <%= link_to "Back to entries", guestbook_with_ai_entries_path %>
</div>