guestbook-rails/config/routes.rb
# == Route Map
#
#                            Prefix Verb   URI Pattern                            Controller#Action
#                                          /assets                                Propshaft::Server
#                          messages GET    /messages(.:format)                    messages#index
#                                   POST   /messages(.:format)                    messages#create
#                       new_message GET    /messages/new(.:format)                messages#new
#                      edit_message GET    /messages/:id/edit(.:format)           messages#edit
#                           message GET    /messages/:id(.:format)                messages#show
#                                   PATCH  /messages/:id(.:format)                messages#update
#                                   PUT    /messages/:id(.:format)                messages#update
#                                   DELETE /messages/:id(.:format)                messages#destroy
#                   test_root_rails GET    /test_root(.:format)                   rails/welcome#index
#                rails_health_check GET    /up(.:format)                          rails/health#show
#                              demo GET    /demo(.:format)                        demos#show
#                              root GET    /                                      home#show
#  turbo_recede_historical_location GET    /recede_historical_location(.:format)  turbo/native/navigation#recede
#  turbo_resume_historical_location GET    /resume_historical_location(.:format)  turbo/native/navigation#resume
# turbo_refresh_historical_location GET    /refresh_historical_location(.:format) turbo/native/navigation#refresh

Rails.application.routes.draw do
  resources :messages
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  if Rails.env.local?
    # a test only route used by spec/features/it_works_spec.rb
    get "test_root", to: "rails/welcome#index", as: "test_root_rails"
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  resource :demo, only: [:show]

  # Defines the root path route ("/")
  root "home#show"
end

guestbook-rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

guestbook-rails/app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id         :integer          not null, primary key
#  body       :text
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Message < ApplicationRecord
end

guestbook-rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

guestbook-rails/app/controllers/concerns/endpoint_testing_concern.rb
# frozen_string_literal: true

# include in the ApplicationController
# class ApplicationController < ActionController::Base
#   include ::EndpointTestingConcern
# end
#
# to be able to pause or error an API in specs
#   When "the sitmulus component is clicked and fetching" do
#     with_api_route_paused(method: :GET, url: demo_path) do
#       demo_page.stimulus_component.click
#       expect(demo_page.stimulus_component.text).to eq "fetching ..."
#     end
#   end

module EndpointTestingConcern
  extend ActiveSupport::Concern

  included do
    before_action :forced_api_error, unless: -> { Rails.env.production? }
    before_action :pause_execution, unless: -> { Rails.env.production? }

    private

    def forced_api_error
      raise Rails.application.config.send(:should_crash)[:error] if disrupt_with?(:should_crash)
    end

    def pause_execution
      Kernel.sleep 0.2 while disrupt_with?(:should_pause)
    end

    def disrupt_with?(method)
      should_disrupt_route_config = Rails.application.config.respond_to?(method) &&
        Rails.application.config.send(method)

      return unless should_disrupt_route_config

      request_for_method_url?(
        method: should_disrupt_route_config[:method],
        url: should_disrupt_route_config[:url],
      )
    end

    def request_for_method_url?(method:, url:)
      method.to_s.downcase.casecmp?(request.method.downcase) &&
        request.url.include?(url)
    end
  end
end

guestbook-rails/app/controllers/demos_controller.rb
# frozen_string_literal: true

class DemosController < ApplicationController
  # @route GET /demo (demo)
  def show
  end
end

guestbook-rails/app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  # @route GET / (root)
  def show
  end
end

guestbook-rails/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[show edit update destroy]

  # GET /messages or /messages.json
  # @route GET /messages (messages)
  def index
    @messages = Message.all
  end

  # GET /messages/1 or /messages/1.json
  # @route GET /messages/:id (message)
  def show
  end

  # @route GET /messages/new (new_message)
  def new
    @message = Message.new
  end

  # @route GET /messages/:id/edit (edit_message)
  def edit
  end

  # POST /messages or /messages.json
  # @route POST /messages (messages)
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: "Message was successfully created." }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  # @route PATCH /messages/:id (message)
  # @route PUT /messages/:id (message)
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  # @route DELETE /messages/:id (message)
  def destroy
    @message.destroy!

    respond_to do |format|
      format.html { redirect_to messages_path, status: :see_other, notice: "Message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_message
    @message = Message.find(params.expect(:id))
  end

  # Only allow a list of trusted parameters through.
  def message_params
    params.expect(message: [:body, :name])
  end
end

guestbook-rails/app/helpers/application_helper.rb
module ApplicationHelper
end

guestbook-rails/app/views/home/show.html.erb
<h1 class="title">BDD Workshop</h1>

guestbook-rails/app/views/layouts/_footer.html.erb
<footer class="footer has-text-centered is-align-content-space-evenly mt-auto">
  <div>
    <%= link_to(
      "Github: bdd-workshop",
      "https://github.com/failure-driven/bdd-workshop",
      target: :_blank,
    ) %> |
    <%= link_to(
      "Github: failure-driven",
      "https://github.com/failure-driven",
      target: :_blank
    ) %> |
    <%= link_to(
      "Failure Driven Blog",
      "https://failure-driven.com",
      target: :_blank
    ) %> |
    <%= link_to(
      "Selena Small (Sessionize)",
      "https://sessionize.com/selena-small/",
      target: :_blank
    ) %> |
    <%= link_to(
      "Michael Milewski (Sessionize)",
      "https://sessionize.com/michael-milewski/",
      target: :_blank
    ) %>
  </div>
  <div>
    <%= image_tag(
      "failure-driven-logo-black.png",
      alt: "BDD Workshop Logo",
      class: "logo-icon",
      size: "32x32",
    ) %>
    © 2025 failure-Driven
  </div>
</footer>

guestbook-rails/app/views/layouts/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to root_path, class: "navbar-item" do%>
      <%= image_tag(
        "failure-driven-logo-black.png",
        alt: "BDD Workshop Logo",
        class: "logo-icon",
        size: "28x28",
      ) %>
      BDD Workshop
    <% end %>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbar">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbar" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to "Home", root_path, class: "navbar-item"%>
      <%= link_to "Guestbook", messages_path, class: "navbar-item"%>
      <%= link_to "Demo", demo_path, class: "navbar-item"%>
    </div>
  </div>
</nav>

guestbook-rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Guestbook Rails" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

<body class="hero is-fullheigh">
  <%= render "layouts/navbar" %>
  <main class="container">
    <%= yield %>
  </main>
  <%= render "layouts/footer" %>
</body>
</html>

guestbook-rails/app/views/messages/_form.html.erb
<%= form_with(model: message) do |form| %>
  <% if message.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :body, class: "label" %>
    <%= form.textarea :body, class: "textarea", rows: 3 %>
  </div>

  <div>
    <%= form.label :name, class: "label" %>
    <%= form.text_field :name, class: "input" %>
  </div>

  <div>
    <%= form.submit class: "button is-link" %>
  </div>
<% end %>

guestbook-rails/app/views/messages/_message.html.erb
<div id="<%= dom_id message %>">
  <p>
    <strong>Body:</strong>
    <%= message.body %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= message.name %>
  </p>

</div>

guestbook-rails/app/views/messages/edit.html.erb
<% content_for :title, "Editing message" %>

<h1 class="title">Editing message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Show this message", @message, class: "button"%>
  <%= link_to "Back to messages", messages_path, class: "button" %>
</div>

guestbook-rails/app/views/messages/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Messages" %>

<h1 class="title">Messages</h1>

<div id="messages">
  <% @messages.each do |message| %>
    <%= render message %>
    <div class="mt-3">
      <%= link_to "Show this message", message, class: "button" %>
    </div>
  <% end %>
</div>

<div class="mt-3">
  <%= link_to "New message", new_message_path, class: "button is-link" %>
</div>

guestbook-rails/app/views/messages/new.html.erb
<% content_for :title, "New message" %>

<h1 class="title">New message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Back to messages", messages_path, class: "button" %>
</div>

guestbook-rails/app/views/messages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @message %>

<div class="mt-3">
  <%= link_to "Edit this message", edit_message_path(@message), class: "button" %>
  <%= link_to "Back to messages", messages_path, class: "button"%>

  <div class="mt-3">
    <%= button_to "Destroy this message", @message, method: :delete, class: "button is-danger" %>
  </div>
</div>