guestbook-rails-minimal/config/routes.rb
Rails.application.routes.draw do
  resources :guestbook_entries
  resources :generated_guestbook_entries, only: [:new, :create, :update]
  resources :messages
  resources :entries
  namespace :guestbook_with_ai do
    resources :entries
    root "entries#index"
  end
  namespace :guestbook_with_ai_full do
    resources :entries
    root "entries#index"
  end
  resources :seed, only: :index
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  if Rails.env.local?
    # a test only route used by spec/features/it_works_spec.rb
    get "test_root", to: "rails/welcome#index", as: "test_root_rails"
  end

  # Defines the root path route ("/")
  root "home#index"
end

guestbook-rails-minimal/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

guestbook-rails-minimal/app/views/home/index.html.erb
<% if notice %>
  <div class="notification">
    <button class="delete"></button>
    <%= notice %>
  </div>
<% end %>

<div>
  <p>
    <%= link_to entries_path, entries_path %>
  </p>
  <p>
    <%= link_to guestbook_with_ai_entries_path, guestbook_with_ai_entries_path %>
  </p>
  <p>
    <%= link_to guestbook_with_ai_full_entries_path, guestbook_with_ai_full_entries_path %>
  </p>
  <p>
    <%= link_to messages_path, messages_path %>
  </p>
  <p>
    <%= link_to guestbook_entries_path, guestbook_entries_path %>
  </p>
  <p>
    <%= link_to seed_index_path, seed_index_path %>
  </p>
</div>